# version: "3.9"

services:
  # Single Postgres instance with multiple databases created by init script
  postgres:
    image: postgres:15
    container_name: instaclone-postgres
    environment:
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: insta_password
      POSTGRES_DB: gateway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./platform/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insta"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: instaclone-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: instaclone-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - miniodata:/data

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: instaclone-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - osdata:/usr/share/opensearch/data

  osdash:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: instaclone-osdash
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

volumes:
  pgdata:
  redisdata:
  miniodata:
  osdata:
